version: 2
defaults: &defaults
  working_directory: ~/repo
#  environment:
jobs:
  build_image:
    <<: *defaults
    docker: 
      - image: gaahrdner/packer-ansible-resource:latest
    steps:
      - checkout
      - run:
          packer build ./packer/ec2_image.json
      
workflows:
  version: 2
  build_deploy:
    jobs:
      - build_image