version: 2
defaults: &defaults
  working_directory: ~/repo
#  environment:
jobs:
  build_image:
    <<: *defaults
    docker: 
      - image: gaahrdner/packer-ansible-resource:latest
    steps:
      - checkout
      - run:
          packer build ./packer/ec2_image.json
  terraform_init:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: terraform_init
          command: terraform init -input=false
      - persist_to_workspace:
          root: ~/repo
          paths: .
  terraform_plan:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: terraform_plan
          command: terraform plan -no-color -out=tfplan  -input=false
      - store_artifacts:
          path: ~/repo/tfplan
          destination: tfplan
      - persist_to_workspace:
          root: ~/repo
          paths: .
  terrafrom_apply:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: terraform_apply
          command: terraform apply -input=false -auto-approve tfplan
      - run:
          name: show
          command: terraform show -no-color > tfresult
      - store_artifacts:
          path: ~/repo/tfresult
          destination: tfresult

workflows:
  version: 2
  build_deploy:
    jobs:
      - build_image
      - init
      - plan:
          requires:
            - init
      - apply:
          requires:
            - plan
          filters:
            branches:
              only: 
                - master